name: cisTEM GPU debug

on:
  workflow_call:

jobs:
  run_build:
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU_debug"
      configure_options: "--enable-gpu-debug --enable-debugmode --with-cuda "
      global_configure_options: " --disable-FastFFT --enable-openmp --enable-experimental --disable-multiple-global-refinements  --disable-multiple-global-refinements --with-wx-config=/opt/WX/icc-static/bin/wx-config "
      runs_on_os: ubuntu-latest
      CC: icc
      CXX: icpc
      cppstandard: 17
      run_console_test: false
      run_samples_functional_testing: false
      run_unit_tests: true
      unit_test_filter: '~[RequiresGPU]'
      n_threads: 4
