name: cisTEMx GPU debug

on:
  workflow_run:
    workflows: ["Check C++ Formatting"]
    types:
      - completed

jobs:
  run_build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU_debug"
      configure_options: "--enable-gpu-debug --enable-debugmode --with-cuda "
      global_configure_options: " --disable-FastFFT --enable-openmp --enable-experimental --enable-staticmode --disable-multiple-global-refinements  --disable-multiple-global-refinements --with-wx-config=/opt/WX/wx305-clang-static-gtk2/bin/wx-config "
      runs_on_os: cpu_2core_runner
      CC: clang
      CXX: clang++
      cppstandard: 17
      run_tests: 'gpu'
      n_threads: 2
