name: cisTEMx cpu debug

on:
  workflow_call:

jobs:
  run_build:
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "cpu_debug"
      configure_options: "--enable-debugmode "
      global_configure_options: " --disable-FastFFT --enable-openmp --enable-experimental --enable-staticmode --disable-multiple-global-refinements  --disable-multiple-global-refinements --with-wx-config=/opt/WX/wx305-clang-static-gtk2/bin/wx-config"
      runs_on_os: ubuntu-latest
      CC: clang
      CXX: clang++
      cppstandard: 17
      run_tests: 'cpu'
      n_threads: 4
