name: cisTEMx GPU release no experimental full build

on:
  workflow_call:

jobs:
  run_build:
    uses: ./.github/workflows/run_builds.yml
    with:
      build_type: "GPU_release_no_experimental_full"
      configure_options: "--with-cuda "
      global_configure_options: "  --disable-FastFFT --enable-openmp --enable-staticmode --disable-multiple-global-refinements  --with-wx-config=/opt/WX/wx305-clang-static-gtk2/bin/wx-config"
      runs_on_os: ubuntu-latest
      CC: clang
      CXX: clang++
      cppstandard: 17
      run_tests: 'cpu'
      n_threads: 4
